# Generated by Django 5.2.7 on 2025-10-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_about_slug_alter_servicecategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
