# Generated by Django 5.2.7 on 2025-10-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='homesection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle2', models.CharField(default='Why Choose Us', max_length=255)),
                ('subcontent2', models.TextField(max_length=255)),
                ('subtitle1', models.CharField(default='Professional Appliance Services You Can Trust', max_length=255)),
                ('subcontent1', models.TextField(max_length=255)),
                ('seo_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.seometadata')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
