# Generated by Django 5.2.7 on 2025-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homesection_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='subcontent3',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homesection',
            name='subtitle3',
            field=models.CharField(default='Professional Appliance Services You Can Trust', max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subtitle1',
            field=models.CharField(default='Welcome to Blue Diamond Service Center', max_length=255),
        ),
    ]
