# Generated by Django 5.2.7 on 2025-10-30 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_homesection_subcontent3_homesection_subtitle3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='seo_metadata',
        ),
        migrations.AddField(
            model_name='homesection',
            name='picture1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/home_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subcontent1',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subcontent2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subcontent3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subtitle2',
            field=models.CharField(default='Professional Appliance Services You Can Trust', max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subtitle3',
            field=models.CharField(default='Why Choose Us', max_length=255),
        ),
    ]
