# Generated by Django 4.2.5 on 2025-10-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_homesection_seo_metadata_homesection_picture1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='training_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='app.trainingcourse'),
        ),
    ]
