# Generated by Django 5.2.7 on 2025-10-30 19:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_companydetails_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Us', max_length=255)),
                ('main_heading', models.CharField(help_text='Main heading for the page', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='Main about us content (supports rich text formatting)')),
                ('main_image', models.ImageField(blank=True, help_text='Main about us image', null=True, upload_to='media/aboutus/')),
                ('side_image', models.ImageField(blank=True, help_text='Side/secondary image', null=True, upload_to='media/aboutus/')),
                ('section_2_title', models.CharField(blank=True, help_text='Second section title (optional)', max_length=255)),
                ('section_2_content', ckeditor.fields.RichTextField(blank=True, help_text='Second section content (optional)')),
                ('section_3_title', models.CharField(blank=True, help_text='Third section title (optional)', max_length=255)),
                ('section_3_content', ckeditor.fields.RichTextField(blank=True, help_text='Third section content (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
    ]
