# Generated by Django 5.2.7 on 2025-10-31 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_aboutuspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='content',
        ),
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=900, verbose_name='short_description'),
            preserve_default=False,
        ),
    ]
