# Generated by Django 5.2.7 on 2025-10-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='card_image',
        ),
    ]
