# Generated by Django 5.2.7 on 2025-11-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_companydetails_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main about us image', null=True, upload_to='aboutus/'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='side_image',
            field=models.ImageField(blank=True, help_text='Side/secondary image', null=True, upload_to='aboutus/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='carousel_images'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='carousel_images'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(upload_to='companydetails/logos/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='picture1',
            field=models.ImageField(upload_to='home_images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='feature_image',
            field=models.ImageField(upload_to='Services/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_courses/'),
        ),
    ]
