# Generated by Django 5.2.7 on 2025-11-02 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_blogpost_video'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Blue Diamond Service Center', max_length=100)),
                ('default_title', models.CharField(help_text='Default page title template', max_length=60)),
                ('default_description', models.CharField(help_text='Default meta description', max_length=160)),
                ('default_keywords', models.CharField(help_text='Default keywords', max_length=255)),
                ('default_og_image', models.ImageField(blank=True, help_text='Default Open Graph image', null=True, upload_to='seo/')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (GA4)', max_length=20)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager ID', max_length=20)),
                ('facebook_app_id', models.CharField(blank=True, help_text='Facebook App ID', max_length=20)),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter handle without @', max_length=50)),
                ('schema_org_type', models.CharField(default='LocalBusiness', help_text='Schema.org type', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default SEO Settings',
                'verbose_name_plural': 'Default SEO Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='seometadata',
            options={'verbose_name': 'SEO Metadata', 'verbose_name_plural': 'SEO Metadata'},
        ),
        migrations.AddField(
            model_name='seometadata',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)'),
        ),
        migrations.AddField(
            model_name='seometadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seometadata',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional)', max_length=160),
        ),
        migrations.AddField(
            model_name='seometadata',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og_images/'),
        ),
        migrations.AddField(
            model_name='seometadata',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional)', max_length=60),
        ),
        migrations.AddField(
            model_name='seometadata',
            name='robots_meta',
            field=models.CharField(default='index,follow', help_text='Robots meta tag', max_length=100),
        ),
        migrations.AddField(
            model_name='seometadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='description',
            field=models.CharField(help_text='Meta description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='keywords',
            field=models.CharField(help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='title',
            field=models.CharField(help_text='SEO title (max 60 chars for best results)', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='seometadata',
            unique_together={('content_type', 'object_id')},
        ),
    ]
