# Generated by Django 4.2.5 on 2025-11-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_defaultseosettings_alter_seometadata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(help_text='SEO title (50-60 chars recommended)', max_length=60)),
                ('meta_description', models.CharField(help_text='Meta description (150-160 chars recommended)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (optional, less important for modern SEO)', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (defaults to meta_title if empty)', max_length=60)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description (defaults to meta_description if empty)', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image - 1200x630px recommended', null=True, upload_to='seo/og_images/')),
                ('og_type', models.CharField(default='website', help_text='Open Graph type (website, article, etc.)', max_length=20)),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=20)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (defaults to meta_title if empty)', max_length=60)),
                ('twitter_description', models.CharField(blank=True, help_text='Twitter description (defaults to meta_description if empty)', max_length=160)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (defaults to og_image if empty) - 1200x628px', null=True, upload_to='seo/twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL (leave empty to auto-generate)')),
                ('robots', models.CharField(default='index, follow', help_text='Robots meta tag (index, follow / noindex, nofollow)', max_length=100)),
                ('schema_type', models.CharField(blank=True, choices=[('Article', 'Article'), ('BlogPosting', 'Blog Posting'), ('Service', 'Service'), ('Course', 'Course'), ('Organization', 'Organization'), ('LocalBusiness', 'Local Business'), ('WebPage', 'Web Page')], help_text='Schema.org type for structured data', max_length=50)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary focus keyword for this page', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='seo_metadata',
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='bing_webmaster_id',
            field=models.CharField(blank=True, help_text='Bing Webmaster verification code', max_length=100),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='business_address',
            field=models.TextField(blank=True, help_text='Business address for schema markup'),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business email for schema markup', max_length=254),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business phone for schema markup', max_length=20),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='google_search_console_id',
            field=models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn company page URL'),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='robots_txt_content',
            field=models.TextField(blank=True, help_text='Custom robots.txt content'),
        ),
        migrations.AddField(
            model_name='defaultseosettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
        migrations.DeleteModel(
            name='SeoMetadata',
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us_page', to='app.seo'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='app.seo'),
        ),
        migrations.AddField(
            model_name='services',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='app.seo'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_course', to='app.seo'),
        ),
    ]
