# Generated by Django 4.2.5 on 2025-11-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_seo_remove_services_seo_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150-160 chars recommended)', max_length=160),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (50-60 chars recommended)', max_length=60),
        ),
    ]
