# Generated by Django 4.2.5 on 2025-11-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_seo_meta_description_alter_seo_meta_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['page_path']},
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('gradient', 'Gradient'), ('solid', 'Solid Color'), ('image', 'Background Image (Legacy)')], default='gradient', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.IntegerField(default=280, help_text='Banner height in pixels'),
        ),
        migrations.AddField(
            model_name='banner',
            name='primary_color',
            field=models.CharField(default='#1e3c72', help_text='Hex color code (e.g., #1e3c72)', max_length=7),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_color',
            field=models.CharField(default='#2a5298', help_text='For gradients - end color', max_length=7),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle or description', max_length=500),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Title and breadcrumb text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text="Only for 'image' type banners", null=True, upload_to='carousel_images'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page_path',
            field=models.CharField(blank=True, help_text='e.g., /services/, /blog/, /about/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Default title (can be overridden by page content)', max_length=255),
        ),
    ]
