# Generated by Django 5.2.7 on 2025-11-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_banner_options_banner_banner_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (50-60 chars recommended)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description (150-160 chars recommended)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (defaults to meta_title if empty)', max_length=60)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description (defaults to meta_description if empty)', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image - 1200x630px recommended', null=True, upload_to='seo/og_images/')),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Twitter card type', max_length=20)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title (defaults to meta_title if empty)', max_length=60)),
                ('twitter_description', models.CharField(blank=True, help_text='Twitter description (defaults to meta_description if empty)', max_length=160)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image (defaults to og_image if empty)', null=True, upload_to='seo/twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL (leave empty to auto-generate)')),
                ('robots', models.CharField(default='index, follow', help_text='Robots meta tag', max_length=100)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary focus keyword for this page', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('about', 'About Us'), ('contact', 'Contact Us'), ('services_list', 'Services List Page'), ('training_list', 'Training Courses List Page'), ('blog_list', 'Blog List Page'), ('gallery', 'Gallery Page')], help_text='Select the page for SEO settings', max_length=50, unique=True)),
                ('schema_type', models.CharField(choices=[('WebPage', 'Web Page'), ('AboutPage', 'About Page'), ('ContactPage', 'Contact Page'), ('CollectionPage', 'Collection Page')], default='WebPage', help_text='Schema.org type for structured data', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable SEO for this page')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO Settings',
                'ordering': ['page'],
            },
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='seo',
            name='robots',
            field=models.CharField(default='index, follow', help_text='Robots meta tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_card',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Twitter card type', max_length=20),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter image (defaults to og_image if empty)', null=True, upload_to='seo/twitter_images/'),
        ),
    ]
