# Generated by Django 5.2.7 on 2025-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_pageseo_alter_seo_meta_keywords_alter_seo_robots_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='services',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
