# Generated by Django 5.2.7 on 2025-11-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_banner_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
